### ISSUE TITLE
Support local dictionaries

### ISSUE THREAD

**Issue by cosmoscalibur** [blopker/codebook#16]
Wooorm dictionaries are not updated.
In Linux, is very common already have installed hunspell dictionaries, but also user could be download hunspell dictionary from upstream source.

Could be added to setup file an option to add hunspell dictionary path to search.

**Comment by blopker** [comment]
I'm working on a better dictionary manager. I'll make sure to include local dictionaries in the design. However, since not all valid dictionaries are parsable right now (as with the updated Spanish dictionary), I wonder if local dictionaries will be very useful. We'll see :)

**Comment by cosmoscalibur** [comment]
Local dictionaries are a good fit to test also compatibility. In my workflow as dictionary maintainer I need to use IDE support of hunspell with local version to use the last own version to test rules. Now, I need to use VSCode for that, but I love Zed and I want to take advantage of Zed to this project also.

**Comment by Drowze** [comment]
Looking forward to this!

Particularly, I'm looking for a way to add a custom dictionary restricted to LUA files on a particular project - more specifically a `neovim` related project (where a lot of words come from the `vim` word and are flagged by codebook)

**Comment by Drowze** [comment]
Any plans here?

My current project uses `cspell` and has a custom dictionary at `cspell-allowed-words.txt`
For context, its `.cspell.yml` looks like this:
```yaml
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: "custom"
    path: "./cspell-allowed-words.txt"
dictionaries:
  - "custom"
ignoreRegExpList: [
    "#*.@\\S+", # skip github nicknames in comments
  ]
overrides:
  - filename: "**/*.{jbuilder,haml}"
    languageId: "ruby"
languageSettings:
  - languageId: "*"
    enabled: false
  - languageId: "ruby"
    enabled: true
  - languageId: "javascript"
    enabled: true
```

And `cspell-allowed-words.txt` looks like:
```
aasm
accessibilities
accessorial
acks
activatable
activerecord
... etc ...
```

With this setup, we can use `cspell` like:
```
$ cat hello-world.rb
def foobar
  puts "Hello, Wrld!"
end

$ npx cspell lint hello-world.rb
1/1 hello-world.rb 254.98ms X
hello-world.rb:2:16 - Unknown word (Wrld)
CSpell: Files checked: 1, Issues found: 1 in 1 file.

# adding a word to our dictionary
$ echo "wrld" >> cspell-allowed-words.txt
$ npx cspell lint hello-world.rb         
CSpell: Files checked: 1, Issues found: 0 in 0 files.
```

Although we're using `cspell` I've been playing quite a bit with `codebook` and I'd love to push us to move to it (especially now that it has a `lint` command - making it viable for CI! 😄 ).
