### ISSUE TITLE
Install as a LSP for helix

### ISSUE THREAD

**Issue by jerabaul29** [blopker/codebook#30]
The readme mentions that it is only available in Zed early on, but then later on it mentions that it is available as a LSP to any editor that supports the LSP prorocol.

- can you provide information about how to install and use the LSP version?
- could you provide a section about how it can be set up specifically helix? :)

**Comment by blopker** [comment]
Hey! Yes, there's only Zed support for now. 

I've seen that each editor has its own quirks when interacting with LSPs, so I'm only a little confident Codebook will work out of the box with another editor. For Helix, I've not actually used it and don't know out of hand how integrations work. I'll leave this issue open, but I can't commit to a timeline for support. Maybe someone else that is familiar with Helix can help out.

**Comment by the-mikedavis** [comment]
I believe this should work out of the box since it looks like the language server isn't using any non-standard extensions.

![codebook-lsp](https://github.com/user-attachments/assets/e39834cd-8cc8-4901-b5f9-6d5f1e19dab6)

```toml
# .helix/languages.toml
[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

# Example use in markdown:
[[language]]
name = "markdown"
language-servers = ["codebook"]
```

**Comment by the-mikedavis** [comment]
To test this I cloned the repo and used `cargo build --release` and used a slightly different configuration (pointing the `command` at the binary):

```toml
[language-server.codebook]
command = "/home/michael/src/codebook/target/release/codebook-lsp"
args = ["serve"]

[[language]]
name = "markdown"
language-servers = ["codebook"]
```

I think it should work to `cargo install` or use one of the binaries from the release page instead.

We could add a default configuration like

```toml
[language-server]
# ...
codebook = { command = "codebook-lsp", args = ["serve"] }
# ...
```

to the default `languages.toml` in the Helix repo and also mention this in https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
